import { useEffect, useMemo, useState } from 'react'
import { getProducts } from '../services/products'
import type { Product } from '../types/product'

const currency = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
function MetricCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className="border border-[#BCA68F] bg-[#FAF8F3] p-5"><p className="text-xs font-semibold tracking-[.12em] text-[#735A45]">{label}</p><p className="mt-4 text-3xl font-semibold tracking-[-.045em] text-[#302A25]">{value}</p><p className="mt-2 text-sm text-[#173F3A]">{detail}</p></article> }
export function DashboardPage() {
  const [products, setProducts] = useState<Product[]>([]); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { getProducts().then(setProducts).catch(() => setError('Não foi possível carregar os dados do estoque.')).finally(() => setIsLoading(false)) }, [])
  const metrics = useMemo(() => ({ units: products.reduce((total, product) => total + product.quantity, 0), value: products.reduce((total, product) => total + product.price * product.quantity, 0), lowStock: products.filter((product) => product.quantity <= 5).length, lowProducts: [...products].sort((a, b) => a.quantity - b.quantity).slice(0, 5) }), [products])
  return <section><div className="flex flex-col justify-between gap-5 border-b border-[#BCA68F] pb-7 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold tracking-[.18em] text-[#735A45]">DOC. ESTOQUE-01</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.045em] text-[#302A25] sm:text-4xl">Visão do estoque</h1><p className="mt-3 max-w-xl leading-7 text-[#735A45]">Indicadores organizados para acompanhar a operação.</p></div><p className="text-sm text-[#735A45]">Atualizado ao abrir a página</p></div>{error && <div role="alert" className="mt-7 border border-[#C99787] bg-[#FFF4EF] px-4 py-3 text-sm text-[#8A3D32]">{error}</div>}{isLoading ? <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="h-35 animate-pulse border border-[#BCA68F] bg-[#FAF8F3]" />)}</div> : <><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="PRODUTOS CADASTRADOS" value={String(products.length)} detail="Itens no catálogo" /><MetricCard label="UNIDADES EM ESTOQUE" value={String(metrics.units)} detail="Soma das quantidades" /><MetricCard label="VALOR DO ESTOQUE" value={currency.format(metrics.value)} detail="Preço × quantidade" /><MetricCard label="ESTOQUE PARA ATENÇÃO" value={String(metrics.lowStock)} detail="Produtos com até 5 un." /></div><section className="mt-7 overflow-hidden border border-[#BCA68F] bg-[#FAF8F3]"><div className="flex items-center justify-between border-b border-[#BCA68F] px-5 py-5"><div><h2 className="font-semibold text-[#302A25]">Estoque para acompanhar</h2><p className="mt-1 text-sm text-[#735A45]">Produtos ordenados por menor quantidade.</p></div><span className="border border-[#BCA68F] bg-[#F5F0E8] px-3 py-1 text-xs font-semibold text-[#173F3A]">{products.length} produtos</span></div>{products.length === 0 ? <div className="px-6 py-14 text-center"><p className="font-medium text-[#302A25]">Seu estoque ainda está vazio.</p><p className="mt-2 text-sm text-[#735A45]">Os produtos cadastrados aparecerão aqui.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-150 text-left"><thead className="bg-[#F5F0E8] text-xs font-semibold tracking-wider text-[#735A45]"><tr><th className="px-5 py-3.5">Produto</th><th className="px-5 py-3.5">Categoria</th><th className="px-5 py-3.5 text-right">Em estoque</th></tr></thead><tbody className="divide-y divide-[#E3D6C7]">{metrics.lowProducts.map((product) => <tr key={product.id} className="text-sm"><td className="px-5 py-4 font-medium text-[#302A25]">{product.name}</td><td className="px-5 py-4 text-[#735A45]">#{product.categoryId}</td><td className="px-5 py-4 text-right"><span className={`border px-3 py-1 text-xs font-semibold ${product.quantity <= 5 ? 'border-[#C99787] bg-[#FFF4EF] text-[#8A3D32]' : 'border-[#A9C0AF] bg-[#EDF4EE] text-[#173F3A]'}`}>{product.quantity} un.</span></td></tr>)}</tbody></table></div>}</section></>}</section>
}
